# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

services:
  - mongo

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - build
  - deploy
  - production

# Jobs:
install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build_and_test:
  stage: build
  before_script:
    - npm run clean
  script:
    - npm run compile:all
    - npm test

coverage:
  stage: build
  script:
    - npm run test:report
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv coverage public
  artifacts:
    paths:
      - public
    expire_in: 30 days

deploy_staging:
  image: ruby:latest
  only:
    - develop
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_STAGING --api-key=$HEROKU_API_KEY
    - echo "Deployed to staging server"

continuous_delivery:
  image: ruby:latest
  dependencies:
    - deploy_staging
  only:
    - develop
  stage: production
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_PROD --api-key=$HEROKU_API_KEY
    - echo "Deployed to production server"
  when: manual